import type { Company, Contact, Project } from "./types";

/**
 * Demo-Datenbestand eines fiktiven TGA-Ingenieurbüros im Rhein-Sieg-Kreis.
 * Dient nur der Anschauung – alle Nummern und Adressen sind erfunden.
 */

const T = "2026-08-20T18:42:00.000Z";

export const OWN_COMPANY_ID = "f-hartmann";

export const COMPANIES: Company[] = [
  {
    id: "f-hartmann",
    name: "Ingenieurbüro Hartmann TGA GmbH",
    category: "intern",
    trade: "Technische Gebäudeausrüstung",
    phone: "02242 90150",
    email: "info@hartmann-tga.de",
    website: "www.hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    notes: "Eigenes Büro. Zentrale ist von 8–17 Uhr besetzt, freitags bis 14 Uhr.",
    projectIds: ["p-26147", "p-26102", "p-25088", "p-26031", "p-25041"],
    updatedAt: T,
  },
  {
    id: "f-mueller",
    name: "Müller Gebäudetechnik GmbH",
    category: "handwerker",
    trade: "Heizungsbauer",
    phone: "02242 123456",
    email: "info@mueller-gebaeudetechnik.de",
    website: "www.mueller-gebaeudetechnik.de",
    address: { street: "Musterstraße 10", zip: "53773", city: "Hennef" },
    notes:
      "Zuverlässiger Partner für Heizung und Sanitär. Eigener Kundendienst mit Notdienst am Wochenende.",
    projectIds: ["p-26147", "p-25088", "p-25041"],
    updatedAt: T,
  },
  {
    id: "f-becker",
    name: "Elektro Becker GmbH & Co. KG",
    category: "handwerker",
    trade: "Elektroinstallation",
    phone: "02241 448820",
    email: "buero@elektro-becker.de",
    website: "www.elektro-becker.de",
    address: { street: "Industriestraße 7", zip: "53721", city: "Siegburg" },
    notes: "Starkstrom, Beleuchtung, BMA. Aufmaß immer vorab per Mail anfordern.",
    projectIds: ["p-26147", "p-26031"],
    updatedAt: T,
  },
  {
    id: "f-klimatec",
    name: "KlimaTec Lüftungsbau GmbH",
    category: "handwerker",
    trade: "Lüftungs- und Klimatechnik",
    phone: "02241 397710",
    email: "kontakt@klimatec-lueftung.de",
    website: "www.klimatec-lueftung.de",
    address: { street: "Am Kanalufer 3", zip: "53840", city: "Troisdorf" },
    notes: "Kanalbau und RLT-Montage. Hygieneinspektion nach VDI 6022 im Haus.",
    projectIds: ["p-26147", "p-26102"],
    updatedAt: T,
  },
  {
    id: "f-thermo",
    name: "Thermo Siegtal Sanitär GmbH",
    category: "handwerker",
    trade: "Sanitär- und Heizungsbau",
    phone: "02243 917640",
    email: "info@thermo-siegtal.de",
    website: "www.thermo-siegtal.de",
    address: { street: "Bachstraße 21", zip: "53783", city: "Eitorf" },
    notes: "Kleinere Sanierungen, kurzfristig verfügbar.",
    projectIds: ["p-26102"],
    updatedAt: T,
  },
  {
    id: "f-schneider",
    name: "Schneider Architekten BDA",
    category: "architekt",
    trade: "Architekturbüro",
    phone: "0228 604410",
    email: "mail@schneider-architekten.de",
    website: "www.schneider-architekten.de",
    address: { street: "Poppelsdorfer Allee 88", zip: "53115", city: "Bonn" },
    notes: "Objektplanung Schul- und Verwaltungsbau. Planlieferung über Projektraum.",
    projectIds: ["p-26147", "p-25088"],
    updatedAt: T,
  },
  {
    id: "f-nordlicht",
    name: "Atelier Nordlicht Architekten",
    category: "architekt",
    trade: "Architekturbüro",
    phone: "0221 5518830",
    email: "post@atelier-nordlicht.de",
    website: "www.atelier-nordlicht.de",
    address: { street: "Venloer Straße 301", zip: "50823", city: "Köln" },
    notes: "Wohnungsbau und Quartiersentwicklung.",
    projectIds: ["p-26031", "p-25041"],
    updatedAt: T,
  },
  {
    id: "f-weber",
    name: "Ingenieurbüro Weber Tragwerksplanung",
    category: "fachplaner",
    trade: "Tragwerksplanung",
    phone: "02241 206730",
    email: "info@weber-tragwerk.de",
    website: "www.weber-tragwerk.de",
    address: { street: "Rathausallee 12", zip: "53757", city: "Sankt Augustin" },
    notes: "Durchbruchsplanung immer vor KW-Ende einreichen.",
    projectIds: ["p-26147", "p-26031"],
    updatedAt: T,
  },
  {
    id: "f-brandschutz",
    name: "BrandSchutz Plus GmbH",
    category: "fachplaner",
    trade: "Brandschutzplanung",
    phone: "0221 934470",
    email: "kontakt@brandschutz-plus.de",
    website: "www.brandschutz-plus.de",
    address: { street: "Aachener Straße 210", zip: "50931", city: "Köln" },
    notes: "Brandschutzkonzepte und Sachverständigenprüfung nach PrüfVO NRW.",
    projectIds: ["p-26147", "p-26102", "p-26031"],
    updatedAt: T,
  },
  {
    id: "f-planelektro",
    name: "PlanElektro Ingenieure GmbH",
    category: "fachplaner",
    trade: "Elektroplanung",
    phone: "0221 776520",
    email: "buero@planelektro.de",
    website: "www.planelektro.de",
    address: { street: "Gladbacher Straße 45", zip: "50672", city: "Köln" },
    notes: "Unterstützt uns bei Elektro-Fachplanung ab LPH 5.",
    projectIds: ["p-26031"],
    updatedAt: T,
  },
  {
    id: "f-viessmann",
    name: "Viessmann Deutschland GmbH",
    category: "hersteller",
    trade: "Wärmeerzeuger / Wärmepumpen",
    phone: "06452 700",
    email: "planerberatung@viessmann.de",
    website: "www.viessmann.de",
    address: { street: "Viessmannstraße 1", zip: "35108", city: "Allendorf (Eder)" },
    notes: "Planerberatung Region West. Auslegungssoftware auf Anfrage.",
    projectIds: ["p-26147", "p-25088"],
    updatedAt: T,
  },
  {
    id: "f-wilo",
    name: "WILO SE",
    category: "hersteller",
    trade: "Pumpentechnik",
    phone: "0231 41020",
    email: "planer@wilo.com",
    website: "www.wilo.de",
    address: { street: "Nortkirchenstraße 100", zip: "44263", city: "Dortmund" },
    notes: "Hydraulischer Abgleich und Pumpenauslegung.",
    projectIds: ["p-26147", "p-26102"],
    updatedAt: T,
  },
  {
    id: "f-trox",
    name: "TROX GmbH",
    category: "hersteller",
    trade: "Lüftungstechnik",
    phone: "02845 2020",
    email: "anwendungstechnik@trox.de",
    website: "www.trox.de",
    address: { street: "Heinrich-Trox-Platz 1", zip: "47504", city: "Neukirchen-Vluyn" },
    notes: "Volumenstromregler, Brandschutzklappen, Luftdurchlässe.",
    projectIds: ["p-26147", "p-26102"],
    updatedAt: T,
  },
  {
    id: "f-kermi",
    name: "Kermi GmbH",
    category: "hersteller",
    trade: "Heizkörper / Flächenheizung",
    phone: "09931 5010",
    email: "info@kermi.de",
    website: "www.kermi.de",
    address: { street: "Pankofen-Bahnhof 1", zip: "94447", city: "Plattling" },
    notes: "Muster und Datenblätter über Außendienst.",
    projectIds: ["p-25088"],
    updatedAt: T,
  },
  {
    id: "f-stadt-hennef",
    name: "Stadt Hennef",
    category: "behoerde",
    trade: "Kommunalverwaltung / Gebäudemanagement",
    phone: "02242 8880",
    email: "info@hennef.de",
    website: "www.hennef.de",
    address: { street: "Frankfurter Straße 97", zip: "53773", city: "Hennef" },
    notes: "Bauherr mehrerer kommunaler Projekte. Rechnungen nur über E-Rechnung.",
    projectIds: ["p-26147", "p-25088"],
    updatedAt: T,
  },
  {
    id: "f-rsk",
    name: "Rhein-Sieg-Kreis – Bauaufsicht",
    category: "behoerde",
    trade: "Untere Bauaufsichtsbehörde",
    phone: "02241 133000",
    email: "bauaufsicht@rhein-sieg-kreis.de",
    website: "www.rhein-sieg-kreis.de",
    address: { street: "Kaiser-Wilhelm-Platz 1", zip: "53721", city: "Siegburg" },
    notes: "Zuständig für Bauanträge und Abnahmen im Kreisgebiet.",
    projectIds: ["p-26147", "p-25041"],
    updatedAt: T,
  },
  {
    id: "f-bezreg",
    name: "Bezirksregierung Köln",
    category: "behoerde",
    trade: "Fördermittel Schulbau",
    phone: "0221 1470",
    email: "poststelle@bezreg-koeln.nrw.de",
    website: "www.bezreg-koeln.nrw.de",
    address: { street: "Zeughausstraße 2-10", zip: "50667", city: "Köln" },
    notes: "Fördermittelabruf für Schulbauprojekte, Verwendungsnachweis jährlich.",
    projectIds: ["p-26147"],
    updatedAt: T,
  },
  {
    id: "f-feuerwehr",
    name: "Feuerwehr Hennef – Vorbeugender Brandschutz",
    category: "behoerde",
    trade: "Brandschutzdienststelle",
    phone: "02242 888400",
    email: "brandschutz@hennef.de",
    website: "www.hennef.de",
    address: { street: "Fritz-Jacobi-Straße 2", zip: "53773", city: "Hennef" },
    notes: "Stellungnahme zu Brandschutzkonzepten, Feuerwehrpläne abstimmen.",
    projectIds: ["p-26147", "p-25088"],
    updatedAt: T,
  },
  {
    id: "f-rheinbau",
    name: "RheinBau Projektentwicklung GmbH",
    category: "bauherr",
    trade: "Projektentwicklung",
    phone: "0228 909180",
    email: "kontakt@rheinbau-pe.de",
    website: "www.rheinbau-pe.de",
    address: { street: "Reuterstraße 155", zip: "53113", city: "Bonn" },
    notes: "Gewerbliche Bauherrin, sehr straffe Terminplanung.",
    projectIds: ["p-26031"],
    updatedAt: T,
  },
  {
    id: "f-wohnbau",
    name: "Wohnbau Rhein-Sieg GmbH",
    category: "bauherr",
    trade: "Wohnungsbaugesellschaft",
    phone: "02241 250700",
    email: "technik@wohnbau-rhein-sieg.de",
    website: "www.wohnbau-rhein-sieg.de",
    address: { street: "Zeithstraße 110", zip: "53721", city: "Siegburg" },
    notes: "Bestandshalterin, Fokus auf Lebenszykluskosten.",
    projectIds: ["p-25041"],
    updatedAt: T,
  },
];

function c(x: Omit<Contact, "updatedAt" | "notes"> & { notes?: string }): Contact {
  return { notes: "", updatedAt: T, ...x };
}

export const CONTACTS: Contact[] = [
  // ── Interne Mitarbeiter ──────────────────────────────────────────────
  c({
    id: "k-hartmann",
    firstName: "Michael",
    lastName: "Hartmann",
    companyId: "f-hartmann",
    position: "Geschäftsführer",
    department: "Geschäftsführung",
    category: "intern",
    phone: "02242 90150",
    extension: "-10",
    mobile: "0170 3344551",
    email: "m.hartmann@hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    favorite: true,
    projectIds: ["p-26147", "p-26031"],
    notes: "Freigaben ab 25.000 € Auftragswert.",
  }),
  c({
    id: "k-krueger",
    firstName: "Sabine",
    lastName: "Krüger",
    companyId: "f-hartmann",
    position: "Projektleiterin",
    department: "Heizung / Sanitär",
    category: "intern",
    phone: "02242 90150",
    extension: "-12",
    mobile: "0170 3344552",
    email: "s.krueger@hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    favorite: true,
    projectIds: ["p-26147", "p-25088"],
    notes: "Projektleitung Schule Hennef und Kita Uckerath.",
  }),
  c({
    id: "k-wolf",
    firstName: "Andreas",
    lastName: "Wolf",
    companyId: "f-hartmann",
    position: "Projektleiter",
    department: "Lüftung / Kälte",
    category: "intern",
    phone: "02242 90150",
    extension: "-14",
    mobile: "0170 3344553",
    email: "a.wolf@hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    favorite: false,
    projectIds: ["p-26147", "p-26102"],
  }),
  c({
    id: "k-lehmann",
    firstName: "Jörg",
    lastName: "Lehmann",
    companyId: "f-hartmann",
    position: "Bauleiter TGA",
    department: "Bauüberwachung",
    category: "intern",
    phone: "02242 90150",
    extension: "-16",
    mobile: "0170 3344554",
    email: "j.lehmann@hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    favorite: true,
    projectIds: ["p-26147", "p-25088", "p-25041"],
    notes: "Meist auf der Baustelle – am besten mobil erreichbar.",
  }),
  c({
    id: "k-bauer",
    firstName: "Nina",
    lastName: "Bauer",
    companyId: "f-hartmann",
    position: "Fachplanerin Elektro",
    department: "Elektrotechnik / MSR",
    category: "intern",
    phone: "02242 90150",
    extension: "-18",
    mobile: "0170 3344555",
    email: "n.bauer@hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    favorite: false,
    projectIds: ["p-26031", "p-26102"],
  }),
  c({
    id: "k-neumann",
    firstName: "Claudia",
    lastName: "Neumann",
    companyId: "f-hartmann",
    position: "Projektleiterin",
    department: "MSR / Gebäudeautomation",
    category: "intern",
    phone: "02242 90150",
    extension: "-19",
    mobile: "0170 3344556",
    email: "c.neumann@hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    favorite: false,
    projectIds: ["p-26102"],
  }),
  c({
    id: "k-fischer",
    firstName: "Daniel",
    lastName: "Fischer",
    companyId: "f-hartmann",
    position: "Technischer Systemplaner",
    department: "Heizung / Sanitär",
    category: "intern",
    phone: "02242 90150",
    extension: "-21",
    mobile: "0170 3344557",
    email: "d.fischer@hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    favorite: false,
    projectIds: ["p-26147"],
  }),
  c({
    id: "k-roth",
    firstName: "Kevin",
    lastName: "Roth",
    companyId: "f-hartmann",
    position: "BIM-Koordinator",
    department: "Digitale Planung",
    category: "intern",
    phone: "02242 90150",
    extension: "-25",
    mobile: "0170 3344558",
    email: "k.roth@hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    favorite: false,
    projectIds: ["p-26031", "p-26147"],
    notes: "Ansprechpartner für IFC-Export und Modellprüfung.",
  }),
  c({
    id: "k-sommer",
    firstName: "Petra",
    lastName: "Sommer",
    companyId: "f-hartmann",
    position: "Sekretariat / Buchhaltung",
    department: "Verwaltung",
    category: "intern",
    phone: "02242 90150",
    extension: "-0",
    mobile: "",
    email: "p.sommer@hartmann-tga.de",
    address: { street: "Frankfurter Straße 42", zip: "53773", city: "Hennef" },
    favorite: true,
    projectIds: [],
    notes: "Zentrale, Rechnungen, Urlaubsplanung.",
  }),

  // ── Handwerker ───────────────────────────────────────────────────────
  c({
    id: "k-mueller",
    firstName: "Thomas",
    lastName: "Müller",
    companyId: "f-mueller",
    position: "Projektleiter",
    department: "Heizung / Sanitär",
    category: "handwerker",
    phone: "02242 123456",
    extension: "-23",
    mobile: "0171 1234567",
    email: "t.mueller@beispiel.de",
    address: { street: "Musterstraße 10", zip: "53773", city: "Hennef" },
    favorite: true,
    projectIds: ["p-26147", "p-25088"],
    notes:
      "Hauptansprechpartner für Heizung und Sanitär bei der Schule Hennef. Erreichbar ab 6:30 Uhr.",
  }),
  c({
    id: "k-becker-max",
    firstName: "Max",
    lastName: "Becker",
    companyId: "f-mueller",
    position: "Bauleiter",
    department: "Heizung / Sanitär",
    category: "handwerker",
    phone: "02242 123456",
    extension: "-27",
    mobile: "0171 1234568",
    email: "m.becker@beispiel.de",
    address: { street: "Musterstraße 10", zip: "53773", city: "Hennef" },
    favorite: false,
    projectIds: ["p-26147"],
  }),
  c({
    id: "k-schmidt-anna",
    firstName: "Anna",
    lastName: "Schmidt",
    companyId: "f-mueller",
    position: "Büro",
    department: "Auftragsabwicklung",
    category: "handwerker",
    phone: "02242 123456",
    extension: "-11",
    mobile: "",
    email: "a.schmidt@beispiel.de",
    address: { street: "Musterstraße 10", zip: "53773", city: "Hennef" },
    favorite: false,
    projectIds: ["p-25041"],
    notes: "Aufmaße, Terminbestätigungen, Rechnungsfragen.",
  }),
  c({
    id: "k-becker-frank",
    firstName: "Frank",
    lastName: "Becker",
    companyId: "f-becker",
    position: "Geschäftsführer",
    department: "Elektrotechnik",
    category: "handwerker",
    phone: "02241 448820",
    extension: "-1",
    mobile: "0172 5560012",
    email: "f.becker@elektro-becker.de",
    address: { street: "Industriestraße 7", zip: "53721", city: "Siegburg" },
    favorite: true,
    projectIds: ["p-26147", "p-26031"],
  }),
  c({
    id: "k-hoffmann",
    firstName: "Sven",
    lastName: "Hoffmann",
    companyId: "f-becker",
    position: "Obermonteur",
    department: "Elektrotechnik",
    category: "handwerker",
    phone: "02241 448820",
    extension: "-14",
    mobile: "0172 5560019",
    email: "s.hoffmann@elektro-becker.de",
    address: { street: "Industriestraße 7", zip: "53721", city: "Siegburg" },
    favorite: false,
    projectIds: ["p-26147"],
  }),
  c({
    id: "k-klein",
    firstName: "Markus",
    lastName: "Klein",
    companyId: "f-klimatec",
    position: "Projektleiter Lüftung",
    department: "Lüftung / Klima",
    category: "handwerker",
    phone: "02241 397710",
    extension: "-32",
    mobile: "0160 7788221",
    email: "m.klein@klimatec-lueftung.de",
    address: { street: "Am Kanalufer 3", zip: "53840", city: "Troisdorf" },
    favorite: false,
    projectIds: ["p-26147", "p-26102"],
    notes: "Kanalnetz und RLT-Zentralen, VDI 6022 Schulung vorhanden.",
  }),
  c({
    id: "k-wagner",
    firstName: "Julia",
    lastName: "Wagner",
    companyId: "f-klimatec",
    position: "Kalkulation",
    department: "Angebotswesen",
    category: "handwerker",
    phone: "02241 397710",
    extension: "-18",
    mobile: "",
    email: "j.wagner@klimatec-lueftung.de",
    address: { street: "Am Kanalufer 3", zip: "53840", city: "Troisdorf" },
    favorite: false,
    projectIds: ["p-26102"],
  }),
  c({
    id: "k-zimmermann",
    firstName: "Ralf",
    lastName: "Zimmermann",
    companyId: "f-thermo",
    position: "Meister / Inhaber",
    department: "Sanitär",
    category: "handwerker",
    phone: "02243 917640",
    extension: "",
    mobile: "0175 2039911",
    email: "r.zimmermann@thermo-siegtal.de",
    address: { street: "Bachstraße 21", zip: "53783", city: "Eitorf" },
    favorite: false,
    projectIds: ["p-26102"],
    notes: "Springt bei kurzfristigen Sanierungen ein.",
  }),

  // ── Hersteller ───────────────────────────────────────────────────────
  c({
    id: "k-berger",
    firstName: "Stefan",
    lastName: "Berger",
    companyId: "f-viessmann",
    position: "Gebietsleiter Planerberatung",
    department: "Wärmeerzeugung",
    category: "hersteller",
    phone: "06452 700",
    extension: "-4821",
    mobile: "0151 22110045",
    email: "berger.stefan@viessmann.de",
    address: { street: "Viessmannstraße 1", zip: "35108", city: "Allendorf (Eder)" },
    favorite: true,
    projectIds: ["p-26147", "p-25088"],
    notes: "Auslegung Wärmepumpenkaskade, kommt für Planerworkshops ins Büro.",
  }),
  c({
    id: "k-vogel",
    firstName: "Katrin",
    lastName: "Vogel",
    companyId: "f-wilo",
    position: "Fachberaterin Planer",
    department: "Pumpentechnik",
    category: "hersteller",
    phone: "0231 41020",
    extension: "-336",
    mobile: "0151 22110088",
    email: "katrin.vogel@wilo.com",
    address: { street: "Nortkirchenstraße 100", zip: "44263", city: "Dortmund" },
    favorite: false,
    projectIds: ["p-26147", "p-26102"],
  }),
  c({
    id: "k-lang",
    firstName: "Dirk",
    lastName: "Lang",
    companyId: "f-trox",
    position: "Anwendungstechnik",
    department: "Lüftungstechnik",
    category: "hersteller",
    phone: "02845 2020",
    extension: "-517",
    mobile: "0151 44220077",
    email: "d.lang@trox.de",
    address: { street: "Heinrich-Trox-Platz 1", zip: "47504", city: "Neukirchen-Vluyn" },
    favorite: false,
    projectIds: ["p-26147", "p-26102"],
    notes: "Auslegung Volumenstromregler und Brandschutzklappen.",
  }),
  c({
    id: "k-simon",
    firstName: "Oliver",
    lastName: "Simon",
    companyId: "f-kermi",
    position: "Außendienst Planerberatung",
    department: "Flächenheizung",
    category: "hersteller",
    phone: "09931 5010",
    extension: "-702",
    mobile: "0151 66330012",
    email: "o.simon@kermi.de",
    address: { street: "Pankofen-Bahnhof 1", zip: "94447", city: "Plattling" },
    favorite: false,
    projectIds: ["p-25088"],
  }),

  // ── Behörden ─────────────────────────────────────────────────────────
  c({
    id: "k-peters",
    firstName: "Ulrike",
    lastName: "Peters",
    companyId: "f-stadt-hennef",
    position: "Leiterin Gebäudemanagement",
    department: "Bauherrenvertretung",
    category: "behoerde",
    phone: "02242 8880",
    extension: "-312",
    mobile: "0151 90011223",
    email: "u.peters@hennef.de",
    address: { street: "Frankfurter Straße 97", zip: "53773", city: "Hennef" },
    favorite: true,
    projectIds: ["p-26147", "p-25088"],
    notes: "Bauherrenvertretung Schule Hennef. Jour fixe dienstags 9 Uhr.",
  }),
  c({
    id: "k-brandt",
    firstName: "Heinz",
    lastName: "Brandt",
    companyId: "f-rsk",
    position: "Sachbearbeiter Bauaufsicht",
    department: "Genehmigungen",
    category: "behoerde",
    phone: "02241 133000",
    extension: "-145",
    mobile: "",
    email: "h.brandt@rhein-sieg-kreis.de",
    address: { street: "Kaiser-Wilhelm-Platz 1", zip: "53721", city: "Siegburg" },
    favorite: false,
    projectIds: ["p-26147", "p-25041"],
    notes: "Telefonisch Mo–Do 8–12 Uhr.",
  }),
  c({
    id: "k-kuhn",
    firstName: "Martina",
    lastName: "Kuhn",
    companyId: "f-bezreg",
    position: "Sachbearbeiterin Förderung",
    department: "Schulbauförderung",
    category: "behoerde",
    phone: "0221 1470",
    extension: "-2280",
    mobile: "",
    email: "martina.kuhn@bezreg-koeln.nrw.de",
    address: { street: "Zeughausstraße 2-10", zip: "50667", city: "Köln" },
    favorite: false,
    projectIds: ["p-26147"],
  }),
  c({
    id: "k-reuter",
    firstName: "Jürgen",
    lastName: "Reuter",
    companyId: "f-feuerwehr",
    position: "Vorbeugender Brandschutz",
    department: "Brandschutzdienststelle",
    category: "behoerde",
    phone: "02242 888400",
    extension: "-6",
    mobile: "0151 77220033",
    email: "j.reuter@hennef.de",
    address: { street: "Fritz-Jacobi-Straße 2", zip: "53773", city: "Hennef" },
    favorite: false,
    projectIds: ["p-26147", "p-25088"],
    notes: "Feuerwehrpläne und Zufahrten vorab abstimmen.",
  }),

  // ── Architekten ──────────────────────────────────────────────────────
  c({
    id: "k-schneider",
    firstName: "Christian",
    lastName: "Schneider",
    companyId: "f-schneider",
    position: "Inhaber / Architekt",
    department: "Objektplanung",
    category: "architekt",
    phone: "0228 604410",
    extension: "-1",
    mobile: "0173 8890021",
    email: "c.schneider@schneider-architekten.de",
    address: { street: "Poppelsdorfer Allee 88", zip: "53115", city: "Bonn" },
    favorite: true,
    projectIds: ["p-26147", "p-25088"],
    notes: "Federführung Planungsbesprechung Schule Hennef.",
  }),
  c({
    id: "k-gruen",
    firstName: "Laura",
    lastName: "Grün",
    companyId: "f-schneider",
    position: "Projektarchitektin",
    department: "Ausführungsplanung",
    category: "architekt",
    phone: "0228 604410",
    extension: "-16",
    mobile: "0173 8890034",
    email: "l.gruen@schneider-architekten.de",
    address: { street: "Poppelsdorfer Allee 88", zip: "53115", city: "Bonn" },
    favorite: false,
    projectIds: ["p-26147"],
  }),
  c({
    id: "k-hofmann",
    firstName: "Bernd",
    lastName: "Hofmann",
    companyId: "f-nordlicht",
    position: "Architekt",
    department: "Wohnungsbau",
    category: "architekt",
    phone: "0221 5518830",
    extension: "-22",
    mobile: "0176 40012234",
    email: "b.hofmann@atelier-nordlicht.de",
    address: { street: "Venloer Straße 301", zip: "50823", city: "Köln" },
    favorite: false,
    projectIds: ["p-26031", "p-25041"],
  }),

  // ── Fachplaner ───────────────────────────────────────────────────────
  c({
    id: "k-weber",
    firstName: "Peter",
    lastName: "Weber",
    companyId: "f-weber",
    position: "Inhaber / Tragwerksplaner",
    department: "Tragwerksplanung",
    category: "fachplaner",
    phone: "02241 206730",
    extension: "-2",
    mobile: "0170 6612290",
    email: "p.weber@weber-tragwerk.de",
    address: { street: "Rathausallee 12", zip: "53757", city: "Sankt Augustin" },
    favorite: false,
    projectIds: ["p-26147", "p-26031"],
    notes: "Durchbrüche > 300 mm immer schriftlich freigeben lassen.",
  }),
  c({
    id: "k-arndt",
    firstName: "Silke",
    lastName: "Arndt",
    companyId: "f-brandschutz",
    position: "Brandschutzsachverständige",
    department: "Brandschutz",
    category: "fachplaner",
    phone: "0221 934470",
    extension: "-31",
    mobile: "0162 3345567",
    email: "s.arndt@brandschutz-plus.de",
    address: { street: "Aachener Straße 210", zip: "50931", city: "Köln" },
    favorite: true,
    projectIds: ["p-26147", "p-26102", "p-26031"],
    notes: "Prüft Entrauchungskonzepte und Schottungen.",
  }),
  c({
    id: "k-engel",
    firstName: "Tobias",
    lastName: "Engel",
    companyId: "f-planelektro",
    position: "Projektleiter Elektro",
    department: "Elektroplanung",
    category: "fachplaner",
    phone: "0221 776520",
    extension: "-40",
    mobile: "0157 33440099",
    email: "t.engel@planelektro.de",
    address: { street: "Gladbacher Straße 45", zip: "50672", city: "Köln" },
    favorite: false,
    projectIds: ["p-26031"],
  }),

  // ── Bauherren ────────────────────────────────────────────────────────
  c({
    id: "k-sander",
    firstName: "Gregor",
    lastName: "Sander",
    companyId: "f-rheinbau",
    position: "Projektentwickler",
    department: "Bauherrenvertretung",
    category: "bauherr",
    phone: "0228 909180",
    extension: "-24",
    mobile: "0176 22330044",
    email: "g.sander@rheinbau-pe.de",
    address: { street: "Reuterstraße 155", zip: "53113", city: "Bonn" },
    favorite: false,
    projectIds: ["p-26031"],
    notes: "Erwartet wöchentliches Kurzprotokoll per Mail.",
  }),
  c({
    id: "k-faber",
    firstName: "Miriam",
    lastName: "Faber",
    companyId: "f-wohnbau",
    position: "Technische Leiterin",
    department: "Bauherrenvertretung",
    category: "bauherr",
    phone: "02241 250700",
    extension: "-55",
    mobile: "0176 22330077",
    email: "m.faber@wohnbau-rhein-sieg.de",
    address: { street: "Zeithstraße 110", zip: "53721", city: "Siegburg" },
    favorite: false,
    projectIds: ["p-25041"],
  }),
];

export const PROJECTS: Project[] = [
  {
    id: "p-26147",
    number: "26147",
    name: "Neubau Schule Hennef",
    city: "Hennef",
    status: "Ausführung",
    lead: "k-krueger",
    notes:
      "Dreizügige Grundschule mit Mensa und Sporthalle. Wärmeerzeugung über Wärmepumpenkaskade, RLT mit WRG, KG 410/420/430.",
    roles: [
      { role: "Bauherr", companyId: "f-stadt-hennef", contactId: "k-peters" },
      { role: "Architekt", companyId: "f-schneider", contactId: "k-schneider" },
      { role: "Projektleitung TGA", companyId: "f-hartmann", contactId: "k-krueger" },
      { role: "Bauleitung TGA", companyId: "f-hartmann", contactId: "k-lehmann" },
      { role: "Heizung / Sanitär", companyId: "f-mueller", contactId: "k-mueller" },
      { role: "Elektro", companyId: "f-becker", contactId: "k-becker-frank" },
      { role: "Lüftung", companyId: "f-klimatec", contactId: "k-klein" },
      { role: "Brandschutz", companyId: "f-brandschutz", contactId: "k-arndt" },
      { role: "Tragwerksplanung", companyId: "f-weber", contactId: "k-weber" },
      { role: "Brandschutzdienststelle", companyId: "f-feuerwehr", contactId: "k-reuter" },
      { role: "Fördermittel", companyId: "f-bezreg", contactId: "k-kuhn" },
    ],
    updatedAt: T,
  },
  {
    id: "p-26102",
    number: "26102",
    name: "Sanierung Rathaus Siegburg",
    city: "Siegburg",
    status: "Planung",
    lead: "k-wolf",
    notes:
      "Denkmalgeschützter Bestand. Schwerpunkt Lüftung und Gebäudeautomation, Heizungsverteilung im Bestand bleibt.",
    roles: [
      { role: "Bauherr", companyId: "f-stadt-hennef", contactId: null },
      { role: "Projektleitung TGA", companyId: "f-hartmann", contactId: "k-wolf" },
      { role: "MSR / GA", companyId: "f-hartmann", contactId: "k-neumann" },
      { role: "Lüftung", companyId: "f-klimatec", contactId: "k-klein" },
      { role: "Sanitär", companyId: "f-thermo", contactId: "k-zimmermann" },
      { role: "Brandschutz", companyId: "f-brandschutz", contactId: "k-arndt" },
      { role: "Pumpentechnik", companyId: "f-wilo", contactId: "k-vogel" },
    ],
    updatedAt: T,
  },
  {
    id: "p-25088",
    number: "25088",
    name: "Neubau Kita Uckerath",
    city: "Hennef-Uckerath",
    status: "Ausführung",
    lead: "k-krueger",
    notes: "Viergruppige Kita, Fußbodenheizung, dezentrale Lüftung mit WRG.",
    roles: [
      { role: "Bauherr", companyId: "f-stadt-hennef", contactId: "k-peters" },
      { role: "Architekt", companyId: "f-schneider", contactId: "k-schneider" },
      { role: "Projektleitung TGA", companyId: "f-hartmann", contactId: "k-krueger" },
      { role: "Bauleitung TGA", companyId: "f-hartmann", contactId: "k-lehmann" },
      { role: "Heizung / Sanitär", companyId: "f-mueller", contactId: "k-mueller" },
      { role: "Flächenheizung", companyId: "f-kermi", contactId: "k-simon" },
      { role: "Wärmeerzeugung", companyId: "f-viessmann", contactId: "k-berger" },
      { role: "Brandschutzdienststelle", companyId: "f-feuerwehr", contactId: "k-reuter" },
    ],
    updatedAt: T,
  },
  {
    id: "p-26031",
    number: "26031",
    name: "Bürogebäude RheinBau Campus",
    city: "Bonn",
    status: "Ausschreibung",
    lead: "k-hartmann",
    notes: "Bürogebäude mit 4.200 m² BGF, Betonkernaktivierung, DGNB Gold angestrebt.",
    roles: [
      { role: "Bauherr", companyId: "f-rheinbau", contactId: "k-sander" },
      { role: "Architekt", companyId: "f-nordlicht", contactId: "k-hofmann" },
      { role: "Projektleitung TGA", companyId: "f-hartmann", contactId: "k-hartmann" },
      { role: "BIM-Koordination", companyId: "f-hartmann", contactId: "k-roth" },
      { role: "Elektroplanung", companyId: "f-planelektro", contactId: "k-engel" },
      { role: "Elektro", companyId: "f-becker", contactId: "k-becker-frank" },
      { role: "Tragwerksplanung", companyId: "f-weber", contactId: "k-weber" },
      { role: "Brandschutz", companyId: "f-brandschutz", contactId: "k-arndt" },
    ],
    updatedAt: T,
  },
  {
    id: "p-25041",
    number: "25041",
    name: "Wohnquartier Siegaue",
    city: "Hennef",
    status: "Abgeschlossen",
    lead: "k-lehmann",
    notes: "36 Wohneinheiten, Nahwärmeanschluss. Gewährleistung läuft bis 03/2030.",
    roles: [
      { role: "Bauherr", companyId: "f-wohnbau", contactId: "k-faber" },
      { role: "Architekt", companyId: "f-nordlicht", contactId: "k-hofmann" },
      { role: "Bauleitung TGA", companyId: "f-hartmann", contactId: "k-lehmann" },
      { role: "Heizung / Sanitär", companyId: "f-mueller", contactId: "k-schmidt-anna" },
      { role: "Bauaufsicht", companyId: "f-rsk", contactId: "k-brandt" },
    ],
    updatedAt: T,
  },
];

/** Vorbelegte "zuletzt verwendet"-Liste, damit das Dashboard sofort gefüllt ist. */
export const INITIAL_RECENT = [
  "k-mueller",
  "k-peters",
  "k-schneider",
  "k-becker-frank",
  "k-lehmann",
  "k-arndt",
];
